var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,c,d){b!=Array.prototype&&b!=Object.prototype&&(b[c]=d.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var b=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+b++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var b=$jscomp.global.Symbol.iterator;b||(b=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[b]&&$jscomp.defineProperty(Array.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(b){var c=0;return $jscomp.iteratorPrototype(function(){return c<b.length?{done:!1,value:b[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(b){$jscomp.initSymbolIterator();b={next:b};b[$jscomp.global.Symbol.iterator]=function(){return this};return b};$jscomp.makeIterator=function(b){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var c=b[Symbol.iterator];return c?c.call(b):$jscomp.arrayIterator(b)};
$jscomp.polyfill=function(b,c,d,e){if(c){d=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var f=b[e];f in d||(d[f]={});d=d[f]}b=b[b.length-1];e=d[b];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:c})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function c(){this.batch_=null}function d(b){return b instanceof f?b:new f(function(c,d){c(b)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;c.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};c.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var e=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(b){e(b,
0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var c=0;c<b.length;++c){var d=b[c];delete b[c];try{d()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};c.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var f=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var c=this.createResolveAndReject_();try{b(c.resolve,c.reject)}catch(n){c.reject(n)}};f.prototype.createResolveAndReject_=
function(){function b(b){return function(e){d||(d=!0,b.call(c,e))}}var c=this,d=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};f.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof f)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var c=null!=b;break a;case "function":c=!0;break a;default:c=!1}c?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};f.prototype.resolveToNonPromiseObj_=function(b){var c=
void 0;try{c=b.then}catch(n){this.reject_(n);return}"function"==typeof c?this.settleSameAsThenable_(c,b):this.fulfill_(b)};f.prototype.reject_=function(b){this.settle_(2,b)};f.prototype.fulfill_=function(b){this.settle_(1,b)};f.prototype.settle_=function(b,c){if(0!=this.state_)throw Error("Cannot settle("+b+", "+c|"): Promise already settled in state"+this.state_);this.state_=b;this.result_=c;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=
this.onSettledCallbacks_,c=0;c<b.length;++c)b[c].call(),b[c]=null;this.onSettledCallbacks_=null}};var g=new c;f.prototype.settleSameAsPromise_=function(b){var c=this.createResolveAndReject_();b.callWhenSettled_(c.resolve,c.reject)};f.prototype.settleSameAsThenable_=function(b,c){var d=this.createResolveAndReject_();try{b.call(c,d.resolve,d.reject)}catch(l){d.reject(l)}};f.prototype.then=function(b,c){function d(b,c){return"function"==typeof b?function(c){try{e(b(c))}catch(q){h(q)}}:c}var e,h,g=new f(function(b,
c){e=b;h=c});this.callWhenSettled_(d(b,e),d(c,h));return g};f.prototype.catch=function(b){return this.then(void 0,b)};f.prototype.callWhenSettled_=function(b,c){function d(){switch(e.state_){case 1:b(e.result_);break;case 2:c(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?g.asyncExecute(d):this.onSettledCallbacks_.push(function(){g.asyncExecute(d)})};f.resolve=d;f.reject=function(b){return new f(function(c,d){d(b)})};f.race=function(b){return new f(function(c,
e){for(var f=$jscomp.makeIterator(b),h=f.next();!h.done;h=f.next())d(h.value).callWhenSettled_(c,e)})};f.all=function(b){var c=$jscomp.makeIterator(b),e=c.next();return e.done?d([]):new f(function(b,f){function h(c){return function(d){g[c]=d;k--;0==k&&b(g)}}var g=[],k=0;do g.push(void 0),k++,d(e.value).callWhenSettled_(h(g.length-1),f),e=c.next();while(!e.done)})};return f},"es6","es3");
$jscomp.executeAsyncGenerator=function(b){function c(c){return b.next(c)}function d(c){return b.throw(c)}return new Promise(function(e,f){function g(b){b.done?e(b.value):Promise.resolve(b.value).then(c,d).then(g,f)}g(b.next())})};
var tObjectCheck,_allowedHostnames=[],_allowedQuerystrings=[],isAllowedDomain,oCONFIG={GWT_UAID:["UA-33523145-1"],GWT_GA4ID:["G-CSLL4ZEK4L"],HOSTNAME_JSON:"https://dap.digitalgov.gov/hostnames.json",QUERYSTRING_JSON:"https://dap.digitalgov.gov/querystrings.json",FORCE_SSL:!0,ANONYMIZE_IP:!0,AGENCY:"",SUB_AGENCY:"",VERSION:"20230725 v6.8 - Dual Tracking",SITE_TOPIC:"",SITE_PLATFORM:"",SCRIPT_SOURCE:"",URL_PROTOCOL:location.protocol,USE_MAIN_CUSTOM_DIMENSIONS:!0,MAIN_AGENCY_CUSTOM_DIMENSION_SLOT:"dimension1",
MAIN_SUBAGENCY_CUSTOM_DIMENSION_SLOT:"dimension2",MAIN_CODEVERSION_CUSTOM_DIMENSION_SLOT:"dimension3",MAIN_SITE_TOPIC_CUSTOM_DIMENSION_SLOT:"dimension4",MAIN_SITE_PLATFORM_CUSTOM_DIMENSION_SLOT:"dimension5",MAIN_SCRIPT_SOURCE_URL_CUSTOM_DIMENSION_SLOT:"dimension6",MAIN_URL_PROTOCOL_CUSTOM_DIMENSION_SLOT:"dimension7",MAIN_INTERACTION_TYPE_CUSTOM_DIMENSION_SLOT:"dimension8",USE_PARALLEL_CUSTOM_DIMENSIONS:!1,PARALLEL_AGENCY_CUSTOM_DIMENSION_SLOT:"dimension1",PARALLEL_SUBAGENCY_CUSTOM_DIMENSION_SLOT:"dimension2",
PARALLEL_CODEVERSION_CUSTOM_DIMENSION_SLOT:"dimension3",PARALLEL_SITE_TOPIC_CUSTOM_DIMENSION_SLOT:"dimension4",PARALLEL_SITE_PLATFORM_CUSTOM_DIMENSION_SLOT:"dimension5",PARALLEL_SCRIPT_SOURCE_URL_CUSTOM_DIMENSION_SLOT:"dimension6",PARALLEL_URL_PROTOCOL_CUSTOM_DIMENSION_SLOT:"dimension7",PARALLEL_INTERACTION_TYPE_CUSTOM_DIMENSION_SLOT:"dimension8",COOKIE_DOMAIN:location.hostname.replace("www.","").toLowerCase(),COOKIE_TIMEOUT:63072E3,SEARCH_PARAMS:"q|querytext|nasaInclude|k|qt",YOUTUBE:!1,AUTOTRACKER:!0,
EXTS:"doc|docx|xls|xlsx|xlsm|ppt|pptx|exe|zip|pdf|js|txt|csv|dxf|dwgd|rfa|rvt|dwfx|dwg|wmv|jpg|msi|7z|gz|tgz|wma|mov|avi|mp3|mp4|csv|mobi|epub|swf|rar",SUBDOMAIN_BASED:!0,PUA_NAME:"GSA_ENOR",GA4_NAME:"GSA_GA4_ENOR"},head=document.getElementsByTagName("head").item(0),GA4Object=document.createElement("script");GA4Object.setAttribute("type","text/javascript");GA4Object.setAttribute("src","https://www.googletagmanager.com/gtag/js?id="+oCONFIG.GWT_GA4ID[0]);head.appendChild(GA4Object);
window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date);"undefined"===typeof window.GoogleAnalyticsObject&&function(b,c,d,e,f,g,k){b.GoogleAnalyticsObject=f;b[f]=b[f]||function(){(b[f].q=b[f].q||[]).push(arguments)};b[f].l=1*new Date;g=c.createElement(d);k=c.getElementsByTagName(d)[0];g.async=1;g.src=e;k.parentNode.insertBefore(g,k)}(window,document,"script","https://www.google-analytics.com/analytics.js","ga");tObjectCheck=window.GoogleAnalyticsObject;
var trackerFlag=!0;function _onEveryPage(){_updateConfig();_defineCookieDomain();_defineAgencyCDsValues();_populateDomains().then(function(b){_allowedHostnames=b._com.concat(b._gov,b._mil,b._org,b._edu,b._net,b._us,b._info,b._cn);isAllowedDomain=_allowedDomains();oCONFIG.YOUTUBE?_initYouTubeTracker():""});_allowedQueries().then(function(b){_allowedQuerystrings=b.default.concat(b[oCONFIG.AGENCY.toLowerCase()]).concat(oCONFIG.SEARCH_PARAMS.split("|"));createTracker(trackerFlag)})}_onEveryPage();
function _defineCookieDomain(){/(([^.\/]+\.[^.\/]{2,3}\.[^.\/]{2})|(([^.\/]+\.)[^.\/]{2,4}))(\/.*)?$/.test(oCONFIG.SUBDOMAIN_BASED.toString())?(oCONFIG.COOKIE_DOMAIN=oCONFIG.SUBDOMAIN_BASED.toLowerCase().replace("www.",""),oCONFIG.SUBDOMAIN_BASED=!0):!1===oCONFIG.SUBDOMAIN_BASED?(oCONFIG.COOKIE_DOMAIN=document.location.hostname.match(/(([^.\/]+\.[^.\/]{2,3}\.[^.\/]{2})|(([^.\/]+\.)[^.\/]{2,4}))(\/.*)?$/)[1],oCONFIG.SUBDOMAIN_BASED=!0):(oCONFIG.COOKIE_DOMAIN=location.hostname.toLowerCase().replace("www.",
""),oCONFIG.SUBDOMAIN_BASED=!1)}function _defineAgencyCDsValues(){oCONFIG.AGENCY=oCONFIG.AGENCY||"unspecified:"+oCONFIG.COOKIE_DOMAIN;oCONFIG.SUB_AGENCY=oCONFIG.SUB_AGENCY||""+oCONFIG.COOKIE_DOMAIN;oCONFIG.SUB_AGENCY=oCONFIG.AGENCY+" - "+oCONFIG.SUB_AGENCY;oCONFIG.SITE_TOPIC=oCONFIG.SITE_TOPIC||"unspecified:"+oCONFIG.COOKIE_DOMAIN;oCONFIG.SITE_PLATFORM=oCONFIG.SITE_PLATFORM||"unspecified:"+oCONFIG.COOKIE_DOMAIN}
function _cleanBooleanParam(b){switch(b.toString().toLowerCase()){case "true":case "on":case "yes":case "1":return!0;case "false":case "off":case "no":case "0":return!1;default:return b}}function _isValidUANum(b){b=b.toLowerCase();b=b.match(/^ua\-([0-9]+)\-[0-9]+$/);return null!=b&&0<b.length}function _isValidGA4Num(b){b=b.toLowerCase();b=b.match(/^g\-([0-9a-z])+$/);return null!=b&&0<b.length}
function _cleanDimensionValue(b){try{pattern=/^dimension([1-9]|[1-9][0-9]|1([0-9][0-9])|200)$/;if(pattern.test(b))return b;if(null!==b.match(/\d+$/g)){var c="dimension"+b.match(/\d+$/g)[0];if(pattern.test(c))return c}return""}catch(d){}}
function _updateConfig(){if("undefined"!==typeof _fedParmsGTM){var b=_fedParmsGTM.toLowerCase().split("&");oCONFIG.SCRIPT_SOURCE="GTM"}else{var c=document.getElementById("_fed_an_ua_tag");_fullParams=c.src.match(/^([^\?]*)(.*)$/i)[2].replace("?","");b=_fullParams.split("&");oCONFIG.SCRIPT_SOURCE=c.src.split("?")[0]}for(c=0;c<b.length;c++)switch(_keyValuePair=decodeURIComponent(b[c].toLowerCase()),_key=_keyValuePair.split("=")[0],_value=_keyValuePair.split("=")[1],_key){case "pua":for(var d=_value.split(","),
e=0;e<d.length;e++)_isValidUANum(d[e])&&oCONFIG.GWT_UAID.push(d[e].toUpperCase());break;case "pga4":d=_value.split(",");for(e=0;e<d.length;e++)_isValidGA4Num(d[e])&&oCONFIG.GWT_GA4ID.push(d[e].toUpperCase());break;case "agency":oCONFIG.AGENCY=_value.toUpperCase();break;case "subagency":oCONFIG.SUB_AGENCY=_value.toUpperCase();break;case "sitetopic":oCONFIG.SITE_TOPIC=_value;break;case "siteplatform":oCONFIG.SITE_PLATFORM=_value;break;case "parallelcd":_value=_cleanBooleanParam(_value);if(!0===_value||
!1===_value)oCONFIG.USE_PARALLEL_CUSTOM_DIMENSIONS=_value;break;case "palagencydim":_value=_cleanDimensionValue(_value);""!==_value&&(oCONFIG.PARALLEL_AGENCY_CUSTOM_DIMENSION_SLOT=_value);break;case "palsubagencydim":_value=_cleanDimensionValue(_value);""!==_value&&(oCONFIG.PARALLEL_SUBAGENCY_CUSTOM_DIMENSION_SLOT=_value);break;case "palversiondim":_value=_cleanDimensionValue(_value);""!==_value&&(oCONFIG.PARALLEL_CODEVERSION_CUSTOM_DIMENSION_SLOT=_value);break;case "paltopicdim":_value=_cleanDimensionValue(_value);
""!==_value&&(oCONFIG.PARALLEL_SITE_TOPIC_CUSTOM_DIMENSION_SLOT=_value);break;case "palplatformdim":_value=_cleanDimensionValue(_value);""!==_value&&(oCONFIG.PARALLEL_SITE_PLATFORM_CUSTOM_DIMENSION_SLOT=_value);break;case "palscriptsrcdim":_value=_cleanDimensionValue(_value);""!==_value&&(oCONFIG.PARALLEL_SCRIPT_SOURCE_URL_CUSTOM_DIMENSION_SLOT=_value);break;case "palurlprotocoldim":_value=_cleanDimensionValue(_value);""!==_value&&(oCONFIG.PARALLEL_URL_PROTOCOL_CUSTOM_DIMENSION_SLOT=_value);break;
case "palinteractiontypedim":_value=_cleanDimensionValue(_value);""!==_value&&(oCONFIG.PARALLEL_INTERACTION_TYPE_CUSTOM_DIMENSION_SLOT=_value);break;case "cto":oCONFIG.COOKIE_TIMEOUT=2628E3*parseInt(_value);break;case "sp":oCONFIG.SEARCH_PARAMS+="|"+_value.replace(/,/g,"|");break;case "exts":oCONFIG.EXTS+="|"+_value.replace(/,/g,"|");break;case "yt":_value=_cleanBooleanParam(_value);if(!0===_value||!1===_value)oCONFIG.YOUTUBE=_value;break;case "autotracker":_value=_cleanBooleanParam(_value);if(!0===
_value||!1===_value)oCONFIG.AUTOTRACKER=_value;break;case "sdor":oCONFIG.SUBDOMAIN_BASED=_cleanBooleanParam(_value)}}function _sendCustomDimensions(b,c){if(0<b.length&&""!==c&&void 0!==c){tObjectCheck!==window.GoogleAnalyticsObject&&createTracker(!1);for(var d=0;d<oCONFIG.GWT_UAID.length;d++)if("dimension0"!==b[d])try{window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",b[d],c)}catch(e){}}}
function _sendCustomMetrics(b,c){if(0<b.length&&""!==c&&void 0!==c){tObjectCheck!=window.GoogleAnalyticsObject&&createTracker(!1);for(var d=0;d<oCONFIG.GWT_UAID.length;d++)if("metric0"!==b[d])try{window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",b[d],c)}catch(e){}}}function _sendEvent(b,c){_mapGA4toUA(b,c);c.send_to=oCONFIG.GA4_NAME;gtag("event",b,c)}
function _mapGA4toUA(b,c){var d;var e=c.link_url;var f=c.event_value?c.event_value:0;var g=c.non_interaction||!1;var k=c.interaction_type;switch(b){case "file_download":c.outbound?d="Outbound Downloads":d="Download";var h=c.file_extension;break;case "email_click":c.outbound?d="Outbound MailTo":d="Mailto";h=c.link_url;e="";break;case "click":d="Outbound";h=c.link_domain;e=c.link_url.split(c.link_domain)[1];break;case "telephone_click":d="Telephone Clicks";h=c.link_url;e="";break;case "video_start":d=
"YouTube Video";h="play";e=c.video_url;break;case "video_play":d="YouTube Video";h="play";e=c.video_url;break;case "video_pause":d="YouTube Video";h="pause";e=c.video_url;break;case "video_progress":d="YouTube Video";h=0<c.video_percent&&33>=c.video_percent?"33%":33<c.video_percent&&66>=c.video_percent?"66%":66<c.video_percent&&90>=c.video_percent?"90%":c.video_percent;e=c.video_url;break;case "video_complete":d="YouTube Video";h="finish";e=c.video_url;break;case "dap_event":d=c.event_category,h=
c.event_action,e=c.event_label}if(""!==d&&void 0!==d&&""!==h&&void 0!==h)for(b=oCONFIG.MAIN_INTERACTION_TYPE_CUSTOM_DIMENSION_SLOT,tObjectCheck!==window.GoogleAnalyticsObject&&createTracker(!1),c=0;c<oCONFIG.GWT_UAID.length;c++)try{0<c&&(!0===oCONFIG.USE_PARALLEL_CUSTOM_DIMENSIONS?b=oCONFIG.PARALLEL_INTERACTION_TYPE_CUSTOM_DIMENSION_SLOT:k=void 0),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+c+".set",b,k),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+c+".send","event",d,h,void 0!==
e?e:"",""===f&&isNaN(f)&&void 0===f?0:parseInt(f),{nonInteraction:g})}catch(n){}}
function _sendPageview(b,c){if(""!==b&&void 0!==b){tObjectCheck!==window.GoogleAnalyticsObject&&createTracker(!1);for(var d=0;d<oCONFIG.GWT_UAID.length;d++)try{window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".send","pageview",{page:b,title:""!==c||void 0!==c?c:document.title})}catch(e){}_sendEvent("page_view",{send_to:oCONFIG.GA4_NAME,page_location:_URIHandler(_scrubbedURL(b)),page_title:""!==c||void 0!==c?c:document.title,ignore_referrer:_isExcludedReferrer()?!0:!1})}}
function gas(b,c,d,e,f,g,k){if(void 0!==b&&""!==b&&void 0!==c&&""!==c&&void 0!==d&&""!==d)if("pageview"===c.toLowerCase())try{_sendPageview(d,void 0===e||""===e?document.title:e)}catch(p){}else if("event"===c.toLowerCase()&&void 0!==e&&""!==e)try{var h=!1;void 0!==k&&"boolean"===typeof _cleanBooleanParam(k)&&(h=_cleanBooleanParam(k));_sendEvent("dap_event",{event_category:d,event_action:e,event_label:void 0===f?"":f,event_value:void 0===g||""===g||isNaN(g)?0:parseInt(g),non_interaction:h})}catch(p){}else if(-1!=
c.toLowerCase().indexOf("dimension"))try{h=c.toLowerCase().split(",");var n=[];dimsPattern=/^dimension([1-9]|[1-9][0-9]|1([0-9][0-9])|200)$/;for(var l=0;l<h.length;l++)if(dimsPattern.test(h[l]))n.push(h[l]);else{var m="dimension"+h[l].match(/\d+$/g)[0];(dimsPattern.test(m)||"dimension0"===m)&&n.push(m)}0<n.length&&_sendCustomDimensions(n,void 0===d?"":d)}catch(p){}else if(-1!=c.toLowerCase().indexOf("metric"))try{n=c.toLowerCase().split(",");h=[];mtrcsPattern=/^metric([1-9]|[1-9][0-9]|1([0-9][0-9])|200)$/;
for(m=0;m<n.length;m++)mtrcsPattern.test(n[m])?h.push(n[m]):(l="metric"+n[m].match(/\d+$/g)[0],(mtrcsPattern.test(l)||"metric0"===l)&&h.push(l));0<h.length&&_sendCustomMetrics(h,void 0===d||""===d||isNaN(d)?1:parseFloat(d))}catch(p){}}function _URIHandler(b){var c=new RegExp("([?&])("+oCONFIG.SEARCH_PARAMS+")(=[^&]*)","i");c.test(b)&&(b=b.replace(c,"$1query$3"));return b}
function _isExcludedReferrer(){if(""!==document.referrer){var b=document.referrer.replace(/https?:\/\//,"").split("/")[0].replace("www.","");return oCONFIG.SUBDOMAIN_BASED?-1!=b.indexOf(oCONFIG.COOKIE_DOMAIN)?!0:!1:b===oCONFIG.COOKIE_DOMAIN?!0:!1}}
function createTracker(b){function c(){dataLayer.push(arguments)}for(var d=0;d<oCONFIG.GWT_UAID.length;d++){var e=_URIHandler(document.location.pathname+document.location.search+document.location.hash);window[window.GoogleAnalyticsObject]("create",oCONFIG.GWT_UAID[d],oCONFIG.COOKIE_DOMAIN,{name:oCONFIG.PUA_NAME+d,allowLinker:!0,cookieExpires:parseInt(oCONFIG.COOKIE_TIMEOUT)});if(oCONFIG.ANONYMIZE_IP)window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set","anonymizeIp",oCONFIG.ANONYMIZE_IP);
if(oCONFIG.FORCE_SSL)window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set","forceSSL",!0);if(_isExcludedReferrer())window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set","referrer","");oCONFIG.USE_MAIN_CUSTOM_DIMENSIONS&&0===d&&(window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",oCONFIG.MAIN_AGENCY_CUSTOM_DIMENSION_SLOT,oCONFIG.AGENCY),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",oCONFIG.MAIN_SUBAGENCY_CUSTOM_DIMENSION_SLOT,oCONFIG.SUB_AGENCY),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+
d+".set",oCONFIG.MAIN_CODEVERSION_CUSTOM_DIMENSION_SLOT,oCONFIG.VERSION),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",oCONFIG.MAIN_SITE_TOPIC_CUSTOM_DIMENSION_SLOT,oCONFIG.SITE_TOPIC),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",oCONFIG.MAIN_SITE_PLATFORM_CUSTOM_DIMENSION_SLOT,oCONFIG.SITE_PLATFORM),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",oCONFIG.MAIN_SCRIPT_SOURCE_URL_CUSTOM_DIMENSION_SLOT,oCONFIG.SCRIPT_SOURCE),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+
d+".set",oCONFIG.MAIN_URL_PROTOCOL_CUSTOM_DIMENSION_SLOT,oCONFIG.URL_PROTOCOL));oCONFIG.USE_PARALLEL_CUSTOM_DIMENSIONS&&0<d&&(window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",oCONFIG.PARALLEL_AGENCY_CUSTOM_DIMENSION_SLOT,oCONFIG.AGENCY),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",oCONFIG.PARALLEL_SUBAGENCY_CUSTOM_DIMENSION_SLOT,oCONFIG.SUB_AGENCY),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",oCONFIG.PARALLEL_CODEVERSION_CUSTOM_DIMENSION_SLOT,oCONFIG.VERSION),
window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",oCONFIG.PARALLEL_SITE_TOPIC_CUSTOM_DIMENSION_SLOT,oCONFIG.SITE_TOPIC),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",oCONFIG.PARALLEL_SITE_PLATFORM_CUSTOM_DIMENSION_SLOT,oCONFIG.SITE_PLATFORM),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",oCONFIG.PARALLEL_SCRIPT_SOURCE_URL_CUSTOM_DIMENSION_SLOT,oCONFIG.SCRIPT_SOURCE),window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".set",oCONFIG.PARALLEL_URL_PROTOCOL_CUSTOM_DIMENSION_SLOT,
oCONFIG.URL_PROTOCOL));-1!==document.title.search(/404|not found/i)&&(e=("/vpv404/"+e).replace(/\/\//g,"/")+"/"+document.referrer);if(b)window[window.GoogleAnalyticsObject](oCONFIG.PUA_NAME+d+".send","pageview",e)}d=document.getElementsByTagName("head").item(0);b=document.createElement("script");b.setAttribute("type","text/javascript");b.setAttribute("src","https://www.googletagmanager.com/gtag/js?id="+oCONFIG.GWT_GA4ID[0]);d.appendChild(b);window.dataLayer=window.dataLayer||[];c("js",new Date);e=
-1!==document.title.search(/404|not found/ig)?document.location.protocol+"//"+document.location.hostname+e:document.location.href;for(d=0;d<oCONFIG.GWT_GA4ID.length;d++)0===d||0<d&&oCONFIG.USE_PARALLEL_CUSTOM_DIMENSIONS?c("config",oCONFIG.GWT_GA4ID[d],{groups:oCONFIG.GA4_NAME,cookie_expires:parseInt(oCONFIG.COOKIE_TIMEOUT),page_location:_URIHandler(_scrubbedURL(e)),ignore_referrer:_isExcludedReferrer()?!0:!1,agency:oCONFIG.AGENCY.toUpperCase(),subagency:oCONFIG.SUB_AGENCY.toUpperCase(),site_topic:oCONFIG.SITE_TOPIC.toLowerCase(),
site_platform:oCONFIG.SITE_PLATFORM.toLowerCase(),script_source:oCONFIG.SCRIPT_SOURCE.toLowerCase(),version:oCONFIG.VERSION.toLowerCase(),protocol:oCONFIG.URL_PROTOCOL}):c("config",oCONFIG.GWT_GA4ID[d],{groups:oCONFIG.GA4_NAME,cookie_expires:parseInt(oCONFIG.COOKIE_TIMEOUT),page_location:_URIHandler(_scrubbedURL(e)),ignore_referrer:_isExcludedReferrer()?!0:!1})}
function _initAutoTracker(b){var c=oCONFIG.COOKIE_DOMAIN,d=oCONFIG.EXTS.split("|");b=b||document.getElementsByTagName("a");for(i=0;i<b.length;i++){var e=0,f="",g=/^mailto:[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}/i,k=/^(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/i,h=/^(tel:)(.*)$/i;if(g.test(b[i].href)||k.test(b[i].href)||h.test(b[i].href)){try{k.test(b[i].href)?f=b[i].hostname.toLowerCase().replace("www.",""):g.test(b[i].href)?f=b[i].href.split("@")[1].toLowerCase():
h.test(b[i].href)&&(f=b[i].href,f=f.toLowerCase())}catch(n){continue}if(oCONFIG.SUBDOMAIN_BASED?-1!==f.indexOf(c):f===c)if(-1!==b[i].href.toLowerCase().indexOf("mailto:")&&-1===b[i].href.toLowerCase().indexOf("tel:"))g=b[i].href.match(/[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}/),_tagClicks(b[i],"email_click",{link_id:b[i].id,link_url:g[0],link_domain:g[0].split("@")[1],link_text:b[i].text.replace(/(?:[\r\n]+)+/g,"").trim(),link_classes:b[i].className});else if(-1===b[i].href.toLowerCase().indexOf("mailto:")&&
-1!==b[i].href.toLowerCase().indexOf("tel:"))_tagClicks(b[i],"telephone_click",{link_id:b[i].id,link_url:b[i].href.split("tel:")[1],link_text:b[i].text.replace(/(?:[\r\n]+)+/g,"").trim(),link_classes:b[i].className});else{if(-1===b[i].href.toLowerCase().indexOf("mailto:")&&-1===b[i].href.toLowerCase().indexOf("tel:"))for(e=0;e<d.length;e++)if(g=b[i].href.split("."),g=g[g.length-1].split(/[#?&?]/),g[0].toLowerCase()===d[e]){_tagClicks(b[i],"file_download",{file_name:b[i].href.split(/[#?&?]/)[0],file_extension:g[0].toLowerCase(),
link_text:b[i].text.replace(/(?:[\r\n]+)+/g,"").trim(),link_id:b[i].id,link_url:b[i].href.replace(/[#?&].*/,""),link_domain:b[i].hostname.replace(/(www\.)?/gi,"")});break}}else for(f=0;f<d.length;f++)if(g=b[i].href.split("."),g=g[g.length-1].split(/[#?]/),g[0].toLowerCase()===d[f]){b[i].href.split(d[f]);_tagClicks(b[i],"file_download",{file_name:b[i].pathname.split(/[#?&?]/)[0],file_extension:g[0].toLowerCase(),link_text:b[i].text.replace(/(?:[\r\n]+)+/g,"").trim(),link_id:b[i].id,link_url:b[i].href.replace(/[#?&].*/,
""),link_domain:b[i].hostname.replace(/(www\.)?/gi,""),outbound:!0});break}else g[0].toLowerCase()!==d[f]&&(e++,e===d.length&&(-1===b[i].href.toLowerCase().indexOf("mailto:")&&-1===b[i].href.toLowerCase().indexOf("tel:")?_tagClicks(b[i],"click",{link_id:b[i].id,link_url:b[i].href.replace(/[#?&].*/,""),link_domain:b[i].hostname.replace(/(www\.)?/gi,""),link_text:b[i].text.replace(/(?:[\r\n]+)+/g,"").trim(),link_classes:b[i].className,outbound:!0}):d.length&&-1!==b[i].href.toLowerCase().indexOf("mailto:")&&
-1===b[i].href.toLowerCase().indexOf("tel:")?(g=b[i].href.match(/[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}/i),_tagClicks(b[i],"email_click",{link_id:b[i].id,link_url:g[0],link_domain:g[0].split("@")[1],link_text:b[i].text.replace(/(?:[\r\n]+)+/g,"").trim(),link_classes:b[i].className,outbound:!0})):d.length&&-1===b[i].href.toLowerCase().indexOf("mailto:")&&-1!==b[i].href.toLowerCase().indexOf("tel:")&&_tagClicks(b[i],"telephone_click",{link_id:b[i].id,link_url:b[i].href.split("tel:")[1],link_text:b[i].text.replace(/(?:[\r\n]+)+/g,
"").trim(),link_classes:b[i].className})))}}}var videoArray_fed=[],playerArray_fed=[],_f33=!1,_f66=!1,_f90=!1,tag=document.createElement("script");tag.src="https://www.youtube.com/iframe_api";var firstScriptTag=document.getElementsByTagName("script")[0];firstScriptTag.parentNode.insertBefore(tag,firstScriptTag);
var youtube_parser_fed=function(b){if((b=b.match(/^(https?:)?(\/\/)?(www\.)?(youtu\.be\/|youtube(\-nocookie)?\.([A-Za-z]{2,4}|[A-Za-z]{2,3}\.[A-Za-z]{2})\/)(watch|embed\/|vi?\/)?(\?vi?=)?([^#&\?\/]{11}).*$/))&&11===b[9].length)return b[9]},IsYouTube_fed=function(b){return/^(https?:)?(\/\/)?(www\.)?(youtu\.be\/|youtube(\-nocookie)?\.([A-Za-z]{2,4}|[A-Za-z]{2,3}\.[A-Za-z]{2})\/)(watch|embed\/|vi?\/)?(\?vi?=)?([^#&\?\/]{11}).*$/.test(b.toString())?!0:!1},YTUrlHandler_fed=function(b){b=b.replace(/origin=(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})&?/gi,
"origin="+document.location.protocol+"//"+document.location.host);stAdd="";adFlag=!1;-1===b.indexOf("https")&&(b=b.replace("http","https"));-1===b.indexOf("?")&&(stAdd="?flag=1");-1===b.indexOf("enablejsapi")&&(stAdd+="&enablejsapi=1",adFlag=!0);-1===b.indexOf("html5")&&(stAdd+="&html5=1",adFlag=!0);-1===b.indexOf("origin")&&(stAdd+="&origin="+document.location.protocol+"//"+document.location.host,adFlag=!0);return!0===adFlag?b+stAdd:b},_initYouTubeTracker=function(){for(var b=document.getElementsByTagName("iframe"),
c=0,d=0;d<b.length;d++){_thisVideoObj=b[d];var e=_thisVideoObj.src;IsYouTube_fed(e)&&(_thisVideoObj.src=YTUrlHandler_fed(e),e=youtube_parser_fed(e),_thisVideoObj.setAttribute("id",e),videoArray_fed[c]=e,c++)}},onYouTubePlayerAPIReady=function(){for(var b=0;b<videoArray_fed.length;b++)playerArray_fed[b]=new YT.Player(videoArray_fed[b],{events:{onReady:onFedPlayerReady,onStateChange:onFedPlayerStateChange}})},onFedPlayerReady=function(b){},onFedPlayerStateChange=function(b){var c=b.target.getIframe().getAttribute("src");
_thisDuration=(parseInt(b.target.getCurrentTime())/parseInt(b.target.getDuration())*100).toFixed();var d={video_current_time:Math.round(b.target.getCurrentTime()),video_duration:Math.round(b.target.getDuration()),video_percent:this.video_percent||Math.round(+_thisDuration),video_provider:"youtube",video_title:b.target.getVideoData().title,video_url:c.split("?")[0]};youtube_parser_fed(c);"undefined"!==typeof onPlayerStateChange&&onPlayerStateChange(b);parseInt(b.data)===parseInt(YT.PlayerState.PLAYING)?
0==Math.floor(+_thisDuration)?(_f90=_f66=_f33=!1,_sendEvent("video_start",d)):_sendEvent("video_play",d):b.data===YT.PlayerState.ENDED?_sendEvent("video_complete",d):b.data===YT.PlayerState.PAUSED&&(_sendEvent("video_pause",d),100>_thisDuration&&(b=_thisDuration,0<b&&33>=b&&!1===_f33?(d.video_percent=33,_sendEvent("video_progress",d),d.video_percent=void 0,_f33=!0):33<b&&66>=b&&!1===_f66?(d.video_percent=66,_sendEvent("video_progress",d),d.video_percent=void 0,_f66=!0):66<b&&90>=b&&!1===_f90&&(d.video_percent=
90,_sendEvent("video_progress",d),d.video_percent=void 0,_f90=!0)))};function _initIdAssigner(){for(var b=document.getElementsByTagName("a"),c=0;c<b.length;c++){var d=b[c].getAttribute("id");null!==d&&""!==d&&void 0!==d||b[c].setAttribute("id","anch_"+c)}}
function _tagClicks(b,c,d){b.addEventListener?(b.addEventListener("mousedown",function(){d.interaction_type="Mouse Click";_sendEvent(c,d)}),b.addEventListener("keydown",function(b){13===b.keyCode&&(d.interaction_type="Enter Key Keystroke",_sendEvent(c,d))})):b.attachEvent&&(b.attachEvent("onmousedown",function(){d.interaction_type="Mouse Click";_sendEvent(c,d)}),b.attachEvent("onkeydown",function(b){13===b.keyCode&&(d.interaction_type="Enter Key Keystroke",_sendEvent(c,d))}))}
function _scrubbedURL(b){RegExp.escape=function(b){return b.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&")};var c=new RegExp("^(https?://(www.)?)?"+RegExp.escape(document.location.hostname.replace("www.","")),"ig");t="";o=c.test(b)?b:document.location.protocol+"//"+document.location.hostname+b;a=o.split("?")[0];return 1<o.split("?").length?(o.split("?")[1].split("&").forEach(function(b,c){-1<_allowedQuerystrings.indexOf(b.split("=")[0])&&(t=t+"&"+b)}),0<t.length?a+"?"+t.substring(1):a):a}
function _allowedQueries(){return $jscomp.executeAsyncGenerator(function(){function b(b,k,l){for(;;)switch(c){case 0:try{return c=3,{value:fetch(oCONFIG.QUERYSTRING_JSON),done:!1}}catch(m){c=1;break}case 3:try{if(1!=b){c=4;break}c=-1;throw l;}catch(m){c=1;break}case 4:try{return f=g=k,c=5,{value:f.json(),done:!1}}catch(m){c=1;break}case 5:try{if(1!=b){c=6;break}c=-1;throw l;}catch(m){c=1;break}case 6:try{return d=e=k,c=-1,{value:d,done:!0}}catch(m){c=1;break}case 1:case 2:c=-1;default:return{value:void 0,
done:!0}}}var c=0,d,e,f,g,k={next:function(c){return b(0,c,void 0)},throw:function(c){return b(1,void 0,c)},return:function(b){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();k[Symbol.iterator]=function(){return this};return k}())}
function _populateDomains(){return $jscomp.executeAsyncGenerator(function(){function b(b,k,l){for(;;)switch(c){case 0:try{return c=3,{value:fetch(oCONFIG.HOSTNAME_JSON),done:!1}}catch(m){c=1;break}case 3:try{if(1!=b){c=4;break}c=-1;throw l;}catch(m){c=1;break}case 4:try{return f=g=k,c=5,{value:f.json(),done:!1}}catch(m){c=1;break}case 5:try{if(1!=b){c=6;break}c=-1;throw l;}catch(m){c=1;break}case 6:try{return d=e=k,c=-1,{value:d,done:!0}}catch(m){c=1;break}case 1:case 2:c=-1;default:return{value:void 0,
done:!0}}}var c=0,d,e,f,g,k={next:function(c){return b(0,c,void 0)},throw:function(c){return b(1,void 0,c)},return:function(b){throw Error("Not yet implemented");}};$jscomp.initSymbolIterator();k[Symbol.iterator]=function(){return this};return k}())}function _allowedDomains(){var b=!1;try{for(var c=0;c<_allowedHostnames.length;c++)if(-1<document.location.hostname.toString().trim().indexOf(_allowedHostnames[c].toString().trim())){b=!0;break}}catch(d){}return b}
function _setUpTrackers(){tObjectCheck!==window.GoogleAnalyticsObject&&createTracker(!1);oCONFIG.ENHANCED_LINK?_initIdAssigner():"";oCONFIG.AUTOTRACKER?_initAutoTracker():""}function _setUpTrackersIfReady(){return"interactive"===document.readyState||"complete"===document.readyState?(_setUpTrackers(),!0):!1}_setUpTrackersIfReady()||(document.addEventListener?document.addEventListener("DOMContentLoaded",_setUpTrackers):document.attachEvent&&document.attachEvent("onreadystatechange",_setUpTrackersIfReady));
//# sourceMappingURL=Federated.js.map
